# Generated by Django 6.0.2 on 2026-02-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_activity_distance_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance_unit',
            field=models.CharField(blank=True, choices=[('Miles', 'mi'), ('Kilometers', 'km'), ('Meters', 'm'), ('Yards', 'yd')], default='Miles', max_length=10, null=True),
        ),
    ]
