# Generated by Django 6.0.2 on 2026-03-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_activity_rpe_alter_dailylog_sleep_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
